name: Update Scholar Stats

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      GOOGLE_SCHOLAR_ID: ${{ secrets.GOOGLE_SCHOLAR_ID }}
    steps:
    - uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install
      run: |
        pip install scholarly

    - name: Run script
      run: |
        python google_scholar_crawler/main.py

    - name: Commit Output
      run: |
        git config --local user.name "GitHub Actions"
        git config --local user.email "actions@github.com"
        git add google_scholar_crawler/stats.json results/*
        git commit -m "Update citation stats" || echo "No changes"
        git push
